# MODULE 1 - PYTHON BASICS

# QUIZZ 1 : Your First Program

In [4]:
# Q1 - radiobouton=3 : Hello  retour ligne World!
print("Hello\nWorld!")

Hello
World!


In [ ]:
# Q2 - radiobouton=3 : there is no output as it is a comment
# print('Hello World!')

# QUIZZ 2 : Types 

In [5]:
# Q1 - radiobouton=2 : 1
int(1.0)

1

In [ ]:
# Q2
bool(1)

# QUIZZ 3 : String Operations

In [6]:
# Q1 - radiobouton=2 : Numbers[::2]
Numbers="0123456"
print(Numbers[::3])
print(Numbers[::2])
print(Numbers[::6])

036
0246
06


In [7]:
# Q2 - radiobouton=2 : 1
"0123456".find('1')

1

# REVIEWS QUESTIONS

In [1]:
# Q1 - radiobouton=2 : 7
3 + 2 * 2

7

In [2]:
# Q2 - radiobouton=3 : Li
name = 'Lizz'
print(name[0:2])

Li


In [3]:
# Q3 - radiobouton=1 : 0246
var = '01234567'
print(var[::2])

0246


In [9]:
# Q4 - radiobouton=3 : '12'
'1'+'2'

'12'

In [11]:
# Q5 - radiobouton=3 : myvar.upper()
myvar = 'hello'
print(len(myvar))
print(myvar.find('hello'))
print(myvar.upper())
# print(myvar.sum())

5
0
HELLO


# MODULE 2 - PYTHON DATA STRUCTURES

# QUIZZ 1 - Lists and Tuples

In [12]:
# Q1 - cases=1 et 3 : A[3] et A[-1]
A=(0,1,2,3)
print(A[3])
print(A[0])
print(A[-1])
# print(A[end])

3
0
3


In [13]:
# Q2 - radiobouton=3 : ['b', 'c']
B=["a","b","c"]
B[1:]

['b', 'c']

# QUIZZ 2 - Sets

In [27]:
# Q1 - radiobouton=1 : {'A', 'B', 'C', 'Z'}
S={'A','B','C'}
U={'A','Z','C'}
U.union(S)

{'A', 'B', 'C', 'Z'}

In [29]:
# Q2 - radiobouton=3 {'A', 'C'}
S={'A','B','C'}
U={'A','Z','C'}
S & U

{'A', 'C'}

# QUIZZ 3 - Dictionnaries

In [14]:
# Q1 - radiobouton=2 : dict_values([0, 1, 2])
D={'a':0,'b':1,'c':2}
D.values()

dict_values([0, 1, 2])

In [15]:
# Q2 - radiobouton=2 : 1 
D={'a':0,'b':1,'c':2}
D['b'] 

1

# REVIEWS QUESTIONS

In [16]:
# Q1 - radiobouton=2 : A[0]
A=('a','b','c')
print(A[1])
print(A[0])
print(A[:])

b
a
('a', 'b', 'c')


In [21]:
# Q2 - radiobouton=1 : True
L=[]
L.append(['a','b'])
len(L)

1

In [ ]:
# Q3 - radiobouton=2 : 0, you can only have one unique element in a set

In [22]:
# Q4 - radiobouton=4 : (4, 4, 4)
Dict={"A":1,"B":"2","C":[3,3,3],"D":(4,4,4),'E':5,'F':6}
Dict["D"]

(4, 4, 4)

In [ ]:
# Q5 - radiobouton=4 : Lists are mutable tuples are not

# MODULE 3 - PYTHON PROGRAMMING FUNDAMENTALS

# QUIZZ 1 - Conditions and Branching

In [25]:
# Q1 - cases=1, 3 et 4
i=1
print(i!=0)
i=0
print(i!=0)
i=-1
print(i!=0)
i=1000000
print(i!=0)

True
False
True
True


In [26]:
# Q2 - radiobouton=2 : this is a
x='a'
if(x!='a'):
    print("this is not a")
else:
    print("this is a")

this is a


# QUIZZ 2 - Loops

In [30]:
# Q1 - radiobouton=3 : 3,4,5 
A=[3,4,5]
for a in A:
    print(a)

3
4
5


In [31]:
# Q2 - radiobouton=1 : 1,2
x=3
y=1
while(y!= x):
    print(y)
    y=y+1

1
2


# QUIZZ 3 - Functions 

In [34]:
# Q1 - radiobouton=3 : 11
a=1
def add(b):
    return a+b
c=add(10)
c

11

In [ ]:
# Q2 - radiobouton=3 : the function is not valid
def f(*x):
    return sum(c)

# QUIZZ 4 - Objects and Classes

In [35]:
class Car(object):
    def __init__(self,make,model,color):
        self.make=make;
        self.model=model;
        self.color=color;
        self.owner_number=0 
    def car_info(self):
        print("make: ",self.make)
        print("model:", self.model)
        print("color:",self.color)
        print("number of owners:",self.owner_number)
    def sell(self):
        self.owner_number=self.owner_number+1

In [37]:
# Q1 - cases=1,2 et 3 
make="Honda"
model="Accord"
color="blue"
c=Car(make="Honda",model="Accord",color="blue")
c.car_info()

make:  Honda
model: Accord
color: blue
number of owners: 0


In [38]:
d=Car("Honda","Accord","blue")
d.car_info()

make:  Honda
model: Accord
color: blue
number of owners: 0


In [39]:
e=Car(model="Accord",make="Honda",color="blue")
e.car_info()

make:  Honda
model: Accord
color: blue
number of owners: 0


In [40]:
f=Car("Accord","Honda","blue")
f.car_info()

make:  Accord
model: Honda
color: blue
number of owners: 0


In [ ]:
# Q2 - radiobouton=1 : utilising the method sell()

# REVIEW QUESTIONS

In [41]:
# Q1 - radiobouton=1 : Hi Mike
x=1
if(x!=1):
    print('Hello')
else:
    print('Hi')
print('Mike')

Hi
Mike


In [42]:
# Q2 - radiobouton=3 : '11,'22','33'
A=['1','2','3']
for a in A:
    print(2*a)

11
22
33


In [44]:
# Q3 - radiobouton=4 : 0
def Delta(x):
    if x==0:
        y=1;
    else:
        y=0;
    return(y)
print(Delta(0))
print(Delta(1))
print(Delta(-15522))

1
0
0


In [45]:
# Q4 - radiobouton=4 : 0
def Delta(x):
    if x==0:
        y=1;
    else:
        y=0;
    return(y)
print(Delta(0))
print(Delta(1))
print(Delta(-15522))

1
0
0


In [47]:
# Q5 - radiobouton=1 : B.sort()
B=[1,5,12,4,52,1,545,6,3,0]
B.sort()
B

[0, 1, 1, 3, 4, 5, 6, 12, 52, 545]

In [49]:
B=[1,5,12,4,52,1,545,6,3,0]
sort(B)
B

NameError: name 'sort' is not defined

In [56]:
B=[1,5,12,4,52,1,545,6,3,0]
C=sorted(B)
print(B,'\n',C)

[1, 5, 12, 4, 52, 1, 545, 6, 3, 0] 
 [0, 1, 1, 3, 4, 5, 6, 12, 52, 545]


In [57]:
# Q6 - radiobouton=3 : dict_keys(['a', 'b'])
{'a':1,'b':2}.keys()

dict_keys(['a', 'b'])

# MODULE - WORKING WITH DATA IN PYTHON 

# QUIZZ 1 - Loading data with Pandas

In [61]:
import pandas as pd

df=pd.DataFrame({'a':[11,21,31],'b':[12,22,32]})
df

a   b
0  11  12
1  21  22
2  31  32

In [60]:
# Q1 - radiobouton=2 : df.iloc[1,0] 21
print(df.iloc[0,1])
print(df.iloc[1,0])
# print(df[1,1])

12
21


In [62]:
# Q2 - radiobouton=1 : yes
import pandas as banana
df=banana.DataFrame({'a':[11,21,31],'b':[21,22,23]})
df.head()

a   b
0  11  21
1  21  22
2  31  23

# QUIZZ 2 - Working with and Saving data with Pandas

In [63]:
# Q1 - radiobouton=2 : bool
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})
df['a']==1

0     True
1    False
2     True
Name: a, dtype: bool

In [ ]:
# Q2 - radiobouton=1 : save a dataframe to a csv file
df.to_csv("file.csv")

# REVIEW QUESTIONS

In [ ]:
# Q1 - radiobouton=1 : Read the file "Example1.txt"
with open("Example1.txt","r") as file1:
    FileContent=file1.readlines()
    print(FileContent)

In [ ]:
# Q2 - radiobouton=2 : Write to the file “Example2.txt
with open("Example2.txt","w") as writefile:
    writefile.write("This is line A\n")
    writefile.write("This is line B\n")

In [ ]:
# Q3 - radiobouton=3 : Append the file "Example3.txt"
with open("Example3.txt","a") as file1:
    file1.write("This is line C\n")

In [64]:
# Q4 - radiobouton=3 : prints the first 5 rows of the dataframe
df.head()

a  b
0  1  1
1  2  1
2  1  1

# QUIZZ 1 - Numpy 1D Arrays

In [66]:
import numpy as np

In [67]:
# Q1 - radiobouton=2 : array([ 1, -1])
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [68]:
# Q2 - radiobouton=3 : 0 
np.dot(np.array([1,-1]),np.array([1,1]))

0

# QUIZZ 2 - Numpy 2D Arrays

In [69]:
# Q1 - radiobouton=2 : 4
A=np.array([[1,2],[3,4],[5,6],[7,8]])
A.shape

(4, 2)

In [70]:
# Q2 - radiobouton=2 : no
A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

# REVIEW QUESTIONS

In [71]:
# Q1 - radiobouton=3 : array([0, 0, 0, 0, 0])
a=np.array([0,1,0,1,0])
b=np.array([1,0,1,0,1])
a*b

array([0, 0, 0, 0, 0])

In [72]:
# Q2 - radiobouton=3 : 0
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)

0

In [73]:
# Q3 - radiobouton=2 : array([11, 11, 11, 11, 11])
a=np.array([1,1,1,1,1])
a+10

array([11, 11, 11, 11, 11])

In [ ]:
# Q4 - radiobouton=1 : np.dot(A,B)